# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-15 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspiration',
            name='onet',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
