# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-29 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_data', '0002_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created_by',
            field=models.CharField(blank=True, default='system', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(blank=True, choices=[('LONGLIST', 'LONGLIST'), ('TXTARR3', 'TXTARR3'), ('TXTMCQ2', 'TXTMCQ2'), ('DP', 'DP'), ('TC', 'TC'), ('LSK', 'LSK'), ('TXTMCQ5', 'TXTMCQ5'), ('TXTMCQ4', 'TXTMCQ4'), ('TXTMCQ3', 'TXTMCQ3'), ('TXT', 'TXT')], max_length=100, null=True),
        ),
    ]
