# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-15 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_data', '0002_auto_20170815_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aspiration',
            old_name='onet',
            new_name='onet_code',
        ),
        migrations.AddField(
            model_name='aspiration',
            name='soc_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
