# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-29 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_data', '0003_auto_20170729_0708'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='answer',
            table='answer',
        ),
        migrations.AlterModelTable(
            name='question',
            table='question',
        ),
    ]
