# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-29 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('add_data', '0004_auto_20170729_0745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.CharField(max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_data.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('members', models.ManyToManyField(through='add_data.Membership', to='add_data.Question')),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_data.Task'),
        ),
    ]
