# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-29 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_data', '0005_auto_20170729_0801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='members',
            new_name='question',
        ),
        migrations.AlterModelTable(
            name='membership',
            table='task_question',
        ),
        migrations.AlterModelTable(
            name='task',
            table='task',
        ),
    ]
