# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-30 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('add_data', '0006_auto_20170729_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'newdata',
            },
        ),
        migrations.CreateModel(
            name='TaskNewDataMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.CharField(max_length=100)),
                ('newdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_data.NewData')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_data.Task')),
            ],
            options={
                'db_table': 'tasknewdatamapping',
            },
        ),
        migrations.AddField(
            model_name='newdata',
            name='question',
            field=models.ManyToManyField(through='add_data.TaskNewDataMapping', to='add_data.Task'),
        ),
    ]
