# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-30 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_data', '0007_auto_20170730_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newdata',
            old_name='question',
            new_name='task',
        ),
    ]
