# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-30 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('add_data', '0008_auto_20170730_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aspiration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'Aspiration',
            },
        ),
        migrations.CreateModel(
            name='TaskAspirationMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.CharField(max_length=100)),
                ('aspiration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_data.Aspiration')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_data.Task')),
            ],
            options={
                'db_table': 'TaskAspirationMapping',
            },
        ),
        migrations.RemoveField(
            model_name='newdata',
            name='task',
        ),
        migrations.RemoveField(
            model_name='tasknewdatamapping',
            name='newdata',
        ),
        migrations.RemoveField(
            model_name='tasknewdatamapping',
            name='task',
        ),
        migrations.DeleteModel(
            name='NewData',
        ),
        migrations.DeleteModel(
            name='TaskNewDataMapping',
        ),
        migrations.AddField(
            model_name='aspiration',
            name='task',
            field=models.ManyToManyField(through='add_data.TaskAspirationMapping', to='add_data.Task'),
        ),
    ]
