# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-30 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_data', '0009_auto_20170730_1627'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aspiration',
            table='Aspiration',
        ),
        migrations.AlterModelTable(
            name='taskaspirationmapping',
            table='TaskAspirationMapping',
        ),
    ]
